//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaThuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Thuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thuoc()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
        [Display(Name = "Mã Thuốc")]
        public int MaThuoc { get; set; }
        [Display(Name = "Tên Thuốc")]
        public string TenThuoc { get; set; }
        [Display(Name = "Đơn Vị Tính")]
        public string DonViTinh { get; set; }
        [Display(Name = "Đơn Giá Sản Phẩm")]
        public Nullable<decimal> DonGia { get; set; }
        [Display(Name = "Mã Loại Thuốc")]
        public Nullable<int> MaLoaiThuoc { get; set; }
        [Display(Name = "Hình Thuốc")]
        public string HinhThuoc { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }

        public virtual LoaiThuoc LoaiThuoc { get; set; }

    }
}



////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace QuanLyNhaThuoc.Models
//{
//    using System;
//    using System.Collections.Generic;

//    public partial class Thuoc
//    {
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//        public Thuoc()
//        {
//            this.CTHDs = new HashSet<CTHD>();
//        }

//        public int MaThuoc { get; set; }
//        public string TenThuoc { get; set; }
//        public string DonViTinh { get; set; }
//        public Nullable<decimal> DonGia { get; set; }
//        public Nullable<int> MaLoaiThuoc { get; set; }
//        public string HinhThuoc { get; set; }

//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//        public virtual ICollection<CTHD> CTHDs { get; set; }
//        public virtual LoaiThuoc LoaiThuoc { get; set; }
//    }
//}
